
spring:
  datasource:
    username: root
    # 本地密码aiqinmeng 远程密码aiqinmeng
    password: 506LAB@CIDP_fzxy
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.128.238.58:3306/bear?serverTimezone=CTT&useUnicode=true&characterEncoding=UTF-8
    #druid
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.bear.bearspringboot.entity # 提取公共包名
  #  设置打印SQL语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


server:
  port: 8080


graduation:
  path: D:/graduation/uploadPath

pageHelper:
  helperDialect: mysql
  reasonable: true  #分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询。
  supportMethodsArguments: true
  params: count=countSql
